name: Run TMDB-Reddit Connector

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  run-connector:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    
    - name: Show package.json content
      run: cat package.json
    
    - name: Clean install of dependencies
      run: npm ci || npm install
    
    - name: Install axios explicitly
      run: npm install axios --save
    
    - name: List installed packages
      run: npm list --depth=0
    
    - name: Run connector script
      run: node src/tmdb-reddit-connector.js