name: Run TMDB-Reddit Connector

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  run-connector:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Debug npm cache
      run: npm config get cache
    
    - name: Direct install of axios and dotenv
      run: |
        npm install axios dotenv
        ls -la node_modules/axios
        ls -la node_modules/dotenv
    
    - name: Run connector script
      run: node src/tmdb-reddit-connector.js