name: Update Spoiler Database

on:
  schedule:
    # Runs at 1 AM UTC every day
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install axios firebase-admin dotenv
        
      - name: Run connector
        run: node tmdb-reddit-connector.js
        env:
          TMDB_API_KEY: ${{ secrets.51092c6cd8e5500a4457ba358eaff91e }}
          REDDIT_CLIENT_ID: ${{ secrets.m5YNP0t0ZZDEI43dKj5E6Q }}
          REDDIT_CLIENT_SECRET: ${{ secrets.Kom_vvM9joAk5mT4M17X6XC1OGqyaA }}
          REDDIT_USERNAME: ${{ secrets.Slight-Jellyfish-893 }}
          REDDIT_PASSWORD: ${{ secrets.U.n3Hm(&JwQ8/UB }}
          FIREBASE_PROJECT_ID: ${{ secrets.spoilerblocker }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.sollin.m@gmail.com }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.AIzaSyDfnkB3th-79lHaRTGOSqx_6f1w2Z2SVJ0 }}
